### ISSUE TITLE
Add more cheats and access to all stages set

### ISSUE THREAD

**Issue by ruthan** [b3dgs/lionheart-remake#300]
Update cheat menu:
- [x] Invincibility
- [x] Add / Remove Heart
- [x] Access to all stages with named set

**Comment by DjThunder** [comment]
Hello, in fact you can select stage set from the launcher (tooltip on mouse over).
I will allow to jump to any stage without having to choose a stage set from Launcher (with cheats sub menu by category).

**Comment by ruthan** [comment]
Hmm there is see only Stages: Original, beginner, veteran.. and does not tell me much.. In cheat menu are just some stage numbers..

**Comment by DjThunder** [comment]
- Original: stages from Lionheart Amiga game (including hard/lionhard difficulty variant)
- Veteran (old name was Alternative in 1.1.0): Hardcore hand made stages
- Beginner (since 1.2.0, by default): Easier stages to play with less headache

Currently, once you chose a stage set (original, veteran, beginner) in Launcher, you can select any stage from this set with cheats (menu or F1 to F10 & 1 to 5).
