### ISSUE TITLE
Add water flickering option

### ISSUE THREAD

**Issue by Ygarr** [b3dgs/lionheart-remake#316]
# TODO
- [x] Allow to choose between original water (flickering) and no flickering water
- [x] Add option to Launcher

# Original comment
Strange not smooth water behavior like this:
![BugLionHeart](https://user-images.githubusercontent.com/14309871/190972205-530e3a97-dac9-456e-beb7-61e01c599c3b.gif)
40-50-60 FPS 

FYI: If make video with 15 FPS water distort almost disappears like here:
![AnimationLionHeart](https://user-images.githubusercontent.com/14309871/190972411-31fe31a0-3642-43ca-90c5-3b156c79a90a.gif)

**Comment by DjThunder** [comment]
Here the original: https://youtu.be/NjV5u-n6NAM?t=908
Water waves are displayed 1/2 or 1/3 per frame (which cause glitch feeling).
I guess it was like this because of fps saving to let more resources for other stuff.
So I kept the same rendering.

Maybe I can add an option to toggle an alternative effect.
I will check that !
